// post
export const GUARDAR_PRODUTO = 'GUARDAR_PRODUTO';
export const GUARDAR_PRODUTO_EXITO = 'GUARDAR_PRODUTO_EXITO';
export const GUARDAR_PRODUTO_ERROR = 'GUARDAR_PRODUTO_ERROR';

// get
export const MOSTRAR_PRODUTO = 'MOSTRAR_PRODUTO';
export const MOSTRAR_PRODUTO_EXITO = 'MOSTRAR_PRODUTO_EXITO';
export const MOSTRAR_PRODUTO_ERROR = 'MOSTRAR_PRODUTO_ERROR';